#!/usr/bin/env python3
"""
Generate every MacroBrief brand asset from one set of constants.

The logo files and the favicon all come from the numbers below, so a change to
the mark is a change to a constant and a re-run — hand-kept copies drift.

    python3 brandbook/build.py
"""

import os

# The family canvas, inherited unchanged.
CANVAS_W, CANVAS_H = 1000.0, 698.86
CX = 500.0

# The globe. Its centre and radius are chosen so it seats in the M's notch —
# the same band the sibling marks put their tiles on — and clears y=0.
GY, R = 196.0, 150.0
# Equator and meridian, as a fraction of R. 0.38 is the ellipse that reads as a
# tilted great circle rather than a flat band, and still opens at 24px.
FORESHORTEN = 0.38
# Knock-out width for the graticule. Below ~14 the lines close at small sizes
# and the globe becomes a plain disc; above ~22 it reads as a wireframe.
SEAM = 18
# The alert dot rides the globe's upper-right limb, on the 45° line.
DOT_R = 42
DOT_X = CX + R * 0.72
DOT_Y = GY - R * 0.72

INK, SIGNAL, PAPER, PAPER_DARK = "#16121a", "#d946ef", "#f6f4f7", "#120f14"

# Measured with fontTools against Open Sans Bold at 440 / -10 tracking (the
# same method reproduces MacroAccount's recorded 3056.91 within 4 units).
WORDMARK_EXTENT = 2368.89
WORDMARK_X = 880
LOCKUP_W = round(WORDMARK_X + WORDMARK_EXTENT)

HERE = os.path.dirname(os.path.abspath(__file__))
LOGOS = os.path.join(HERE, "logos")

M_PATH = (
    "M1000,281.63v340c0,10.67-6.26,20.42-16.01,25.04l-107.66,49.57c-18.47,8.52-39.61-4.82-39.61-25.04v-168.72"
    "l-302.13,139.16c-21.96,10.16-47.21,10.16-68.97,0l-302.13-139.16v168.72c0,20.22-21.24,33.56-39.72,25.04"
    "l-107.66-49.57c-9.85-4.62-16.11-14.37-16.11-25.04v-340c0-18.68,18.37-31.51,35.71-26.48,1.33.41,2.67.92,3.9,1.44"
    "l429.49,197.97c19.6,9.03,42.28,9.03,61.78,0l429.49-197.97c1.03-.41,2.26-.92,3.39-1.33,17.65-5.44,36.23,7.49,36.23,26.38Z"
)

_uid = [0]


def _mask():
    """The graticule — equator, meridian and the horizon line — as a knock-out."""
    _uid[0] += 1
    mid = f"mbgrat{_uid[0]}"
    ry = R * FORESHORTEN
    return mid, (
        f'<mask id="{mid}"><rect width="{CANVAS_W:.0f}" height="{CANVAS_H}" fill="#fff"/>'
        f'<ellipse cx="{CX:.0f}" cy="{GY:.0f}" rx="{R:.0f}" ry="{ry:.1f}" fill="none" stroke="#000" stroke-width="{SEAM}"/>'
        f'<ellipse cx="{CX:.0f}" cy="{GY:.0f}" rx="{ry:.1f}" ry="{R:.0f}" fill="none" stroke="#000" stroke-width="{SEAM}"/>'
        f'<line x1="{CX-R:.0f}" y1="{GY:.0f}" x2="{CX+R:.0f}" y2="{GY:.0f}" stroke="#000" stroke-width="{SEAM}"/>'
        f"</mask>"
    )


def globe(body, accent):
    mid, mask = _mask()
    return mask, (
        f'<circle cx="{CX:.0f}" cy="{GY:.0f}" r="{R:.0f}" fill="{body}" mask="url(#{mid})"/>'
        f'<circle cx="{DOT_X:.0f}" cy="{DOT_Y:.0f}" r="{DOT_R}" fill="{accent}"/>'
    )


HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  MacroBrief isotype{note}

  Family geometry, inherited unchanged: the isometric M on the 1000 x 698.86
  canvas, with the mark's object seated in the M's notch on the same band the
  sibling tiles sit on.

  What sits in the notch is what differs, and it is the only part that carries
  meaning. MacroBrief's object is a GLOBE — the news icon everyone already
  reads — with its equator and one meridian knocked out as transparent lines,
  and a single dot on its upper-right limb: the alert, the one item out of the
  whole world that is worth pushing to you today.

  The graticule is knocked out, not painted, in every variant: filled solid the
  globe is a plain disc and could be a coin or a period.

  Generated by brandbook/build.py. Do not hand-edit.
-->
"""


def isotype(m, body, accent, note=""):
    mask, group = globe(body, accent)
    return HEADER.format(note=note) + (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS_W:.0f} {CANVAS_H}" role="img" aria-label="MacroBrief">\n'
        f"  <title>MacroBrief</title>\n  {mask}\n"
        f'  <path fill="{m}" d="{M_PATH}"/>\n  {group}\n</svg>\n'
    )


def lockup(m, body, accent, macro, suffix, note=""):
    mask, group = globe(body, accent)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!--\n  MacroBrief imagotipo{note}\n\n"
        f"  Family lockup metrics: isotype at scale(0.72) translated (0, 97.8),\n"
        f"  wordmark in Open Sans Bold at 440 with -10 tracking, baseline y=512 from\n"
        f"  x={WORDMARK_X}. The canvas is that offset plus the wordmark's MEASURED extent\n"
        f"  ({WORDMARK_EXTENT}), not a round number chosen by eye.\n\n"
        f"  Generated by brandbook/build.py. Do not hand-edit.\n-->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {LOCKUP_W} {CANVAS_H}" role="img" aria-label="MacroBrief">\n'
        f"  <title>MacroBrief</title>\n  {mask}\n"
        f'  <g transform="translate(0,97.8) scale(0.72)">\n'
        f'    <path fill="{m}" d="{M_PATH}"/>\n    {group}\n  </g>\n'
        f'  <text x="{WORDMARK_X}" y="512" font-family="Open Sans, ui-sans-serif, system-ui, sans-serif"\n'
        f'        font-weight="700" font-size="440" letter-spacing="-10">\n'
        f'    <tspan fill="{macro}">Macro</tspan><tspan fill="{suffix}">Brief</tspan>\n'
        f"  </text>\n</svg>\n"
    )


def favicon():
    # Centre the mark's TRUE bounding box (globe top down to the M's foot), not
    # the canvas — a 16px tab cannot spare the wasted height.
    top = GY - R
    mark_h = CANVAS_H - top
    offset = (CANVAS_W - mark_h) / 2 - top
    mask, group = globe("#ffffff", SIGNAL)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- MacroBrief favicon. Dark-ground colours on a transparent square, centred\n"
        "     on the mark's real bounding box; never stretched — the mark is wider than\n"
        "     tall, so a square canvas letterboxes. Generated by brandbook/build.py. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" role="img" aria-label="MacroBrief">\n'
        f"  <title>MacroBrief</title>\n  {mask}\n"
        f'  <g transform="translate(0,{offset:.2f})">\n'
        f'    <path fill="{SIGNAL}" d="{M_PATH}"/>\n    {group}\n  </g>\n</svg>\n'
    )


def write_logos():
    os.makedirs(LOGOS, exist_ok=True)
    white = "#ffffff"
    files = {
        "isotype.svg": isotype(INK, INK, SIGNAL),
        "isotype-dark-bg.svg": isotype(SIGNAL, white, SIGNAL, " — for dark backgrounds"),
        "isotype-black.svg": isotype("#000000", "#000000", "#000000", " — single ink, black"),
        "isotype-white.svg": isotype(white, white, white, " — single ink, white"),
        "imagotipo.svg": lockup(INK, INK, SIGNAL, INK, SIGNAL),
        "imagotipo-dark-bg.svg": lockup(SIGNAL, white, SIGNAL, white, SIGNAL, " — for dark backgrounds"),
        "imagotipo-black.svg": lockup("#000000", "#000000", "#000000", "#000000", "#000000", " — single ink"),
        "imagotipo-white.svg": lockup(white, white, white, white, white, " — single ink"),
        "favicon.svg": favicon(),
    }
    for name, content in files.items():
        with open(os.path.join(LOGOS, name), "w") as handle:
            handle.write(content)
    return sorted(files)


if __name__ == "__main__":
    written = write_logos()
    print(f"logos: {len(written)} files -> {LOGOS}")
